{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2b17dcb4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7aa54471",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_customers_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_customers','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_customers;\n",
    "\n",
    "CREATE TABLE bronze.olist_customers (\n",
    "    customer_id CHAR(32),\n",
    "    customer_unique_id CHAR(32),\n",
    "    customer_zip_code_prefix CHAR(8),\n",
    "    customer_city NVARCHAR(100),\n",
    "    customer_state CHAR(2)\n",
    ")\n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_customers_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_customers ({cols}) VALUES ({placeholders})\"\n",
    "\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_customers_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "74e04219",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_geolocation_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_geolocation','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_geolocation;\n",
    "\n",
    "CREATE TABLE bronze.olist_geolocation (\n",
    "    geolocation_zip_code_prefix CHAR(8),\n",
    "    geolocation_lat FLOAT,\n",
    "    geolocation_lng FLOAT,\n",
    "    geolocation_city NVARCHAR(100),\n",
    "    geolocation_state CHAR(4)\n",
    ")\n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_geolocation_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_geolocation ({cols}) VALUES ({placeholders})\"\n",
    "\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_geolocation_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ee1d5e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_geolocation_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_order_items','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_order_items;\n",
    "\n",
    "CREATE TABLE bronze.olist_order_items (\n",
    "    order_id CHAR(32),\n",
    "    order_item_id INT,\n",
    "    product_id CHAR(32),\n",
    "    seller_id CHAR(32),\n",
    "    shipping_limit_date DATETIME2(0),\n",
    "    PRICE FLOAT,\n",
    "    freight_value FLOAT\n",
    ")\n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_order_items_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_order_items ({cols}) VALUES ({placeholders})\"\n",
    "\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_order_items_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "480fe5ac",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_order_payments_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_order_payments','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_order_payments;\n",
    "\n",
    "CREATE TABLE bronze.olist_order_payments (\n",
    "    order_id CHAR(32),\n",
    "    payment_sequential INT,\n",
    "    payment_type NVARCHAR(50),\n",
    "    payment_installments INT,\n",
    "    payment_value FLOAT\n",
    ")\n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_order_payments_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_order_payments ({cols}) VALUES ({placeholders})\"\n",
    "\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_order_payments_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b422f09c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_order_reviews_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_order_reviews','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_order_reviews;\n",
    "\n",
    "CREATE TABLE bronze.olist_order_reviews (\n",
    "    review_id CHAR(32),\n",
    "    order_id CHAR(32),\n",
    "    review_score FLOAT,\n",
    "    review_comment_title NVARCHAR(500),\n",
    "    review_comment_message NVARCHAR(500),\n",
    "    review_creation_date DATETIME2(0),\n",
    "    review_answer_timestamp DATETIME2(0)\n",
    ")\n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_order_reviews_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_order_reviews ({cols}) VALUES ({placeholders})\"\n",
    "df = df.where(pd.notnull(df), None)\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_order_reviews_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6f27f543",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_orders_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_orders','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_orders;\n",
    "\n",
    "CREATE TABLE bronze.olist_orders (\n",
    "    order_id CHAR(32),\n",
    "    customer_id CHAR(32),\n",
    "    order_status NVARCHAR(50),\n",
    "    order_purchase_timestamp DATETIME2(0),\n",
    "    order_approved_at DATETIME2(0),\n",
    "    order_delivered_carrier_date DATETIME2(0),\n",
    "    order_delivered_customer_date DATETIME2(0),\n",
    "    order_estimated_delivery_date DATETIME2(0)\n",
    ")\n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_orders_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_orders ({cols}) VALUES ({placeholders})\"\n",
    "df = df.where(pd.notnull(df), None)\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_orders_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "8e7f22af",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_products_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_products','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_products;\n",
    "\n",
    "CREATE TABLE bronze.olist_products (\n",
    "    product_id CHAR(32),\n",
    "    product_category_name NVARCHAR(100),\n",
    "    product_name_lenght BIGINT,\n",
    "    product_description_lenght BIGINT,\n",
    "    product_photos_qty BIGINT,\n",
    "    product_weight_g BIGINT,\n",
    "    product_length_cm BIGINT,\n",
    "    product_height_cm BIGINT,\n",
    "    product_width_cm BIGINT\n",
    ") \n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_products_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_products ({cols}) VALUES ({placeholders})\"\n",
    "df = df.where(pd.notnull(df), None)\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_products_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "a9f3d490",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "olist_sellers_dataset CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.olist_sellers','U') IS NOT NULL\n",
    "    DROP TABLE bronze.olist_sellers;\n",
    "\n",
    "CREATE TABLE bronze.olist_sellers (\n",
    "    seller_id CHAR(32),\n",
    "    seller_zip_code_prefix char(8),\n",
    "    seller_city NVARCHAR(50),\n",
    "    seller_state NVARCHAR(10),\n",
    ") \n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\olist_sellers_dataset.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.olist_sellers ({cols}) VALUES ({placeholders})\"\n",
    "df = df.where(pd.notnull(df), None)\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"olist_sellers_dataset CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "a2f8928e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "product_category_name_translation CSV가 bronze 스키마에 적재 완료\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import pyodbc\n",
    "\n",
    "# =====================================================\n",
    "# SQL Server 연결 정보 (Windows 인증)\n",
    "# =====================================================\n",
    "server = 'localhost\\\\SQLEXPRESS'  # SQL Server 이름, 인스턴스가 있으면 붙여주기\n",
    "database = 'E_Commerce'         # 데이터베이스 이름\n",
    "\n",
    "conn_str = f\"\"\"\n",
    "DRIVER={{ODBC Driver 17 for SQL Server}};\n",
    "SERVER={server};\n",
    "DATABASE={database};\n",
    "Trusted_Connection=yes;\n",
    "\"\"\"\n",
    "\n",
    "conn = pyodbc.connect(conn_str)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# =====================================================\n",
    "# Bronze Layer 스키마/테이블 생성\n",
    "# =====================================================\n",
    "# dbo 대신 bronze 스키마 사용\n",
    "cursor.execute(\"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'bronze') EXEC('CREATE SCHEMA bronze');\")\n",
    "conn.commit()\n",
    "\n",
    "# 테이블 생성\n",
    "create_table_sql = \"\"\"\n",
    "IF OBJECT_ID('bronze.product_category_name_translation','U') IS NOT NULL\n",
    "    DROP TABLE bronze.product_category_name_translation;\n",
    "\n",
    "CREATE TABLE bronze.product_category_name_translation (\n",
    "    product_category_name NVARCHAR(50),\n",
    "    product_category_name_english NVARCHAR(50)\n",
    ") \n",
    "\"\"\"\n",
    "cursor.execute(create_table_sql)\n",
    "\n",
    "conn.commit()\n",
    "\n",
    "# =====================================================\n",
    "# CSV 파일 경로\n",
    "# =====================================================\n",
    "csv_path = r'C:\\Olist\\product_category_name_translation.csv'  # 실제 CSV 경로\n",
    "\n",
    "# =====================================================\n",
    "# CSV → SQL Server 적재\n",
    "# =====================================================\n",
    "df = pd.read_csv(csv_path, encoding='utf-8')  # UTF-8 CSV\n",
    "df.columns = [c.lower() for c in df.columns]  # 컬럼 이름 소문자로 통일\n",
    "\n",
    "cursor.fast_executemany = True  # 대용량 삽입 최적화\n",
    "cols = ','.join(df.columns)\n",
    "placeholders = ','.join(['?'] * len(df.columns))\n",
    "sql_insert = f\"INSERT INTO bronze.product_category_name_translation ({cols}) VALUES ({placeholders})\"\n",
    "df = df.where(pd.notnull(df), None)\n",
    "cursor.executemany(sql_insert, df.values.tolist())\n",
    "conn.commit()\n",
    "\n",
    "print(\"product_category_name_translation CSV가 bronze 스키마에 적재 완료\")\n",
    "\n",
    "cursor.close()\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "dacfe8a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
